# 오류 처리

---

- 스위프트에서 오류(Error)는 **`Error`**라는 프로토콜을 준수하는 타입의 값을 통해 표현
- **`Error`** 프로토콜은 사실상 요구사항이 없는 빈 프로토콜일 뿐이지만, 오류를 표현하기 위한 타입(주로 **열거형**)은 이 프로토콜을 채택
- 스위프트의 **열거형 `enum`**은 오류의 종류를 나타내기에 아주 적합한 기능
- 연관 값을 통해 오류에 관한 부가 정보를 제공할 수도 있음

## 오류 표현

- **`Error`** 프로토콜을 채택하여 (주로) 열거형을 통해서 오류를 표현
- 자판기 기능을 하는 `VendingMachine` 클래스를 예제로 사용

```swift
// 발생할 수 있는 오류의 종류를 모아둔 enum 타입에 Error 프로토콜을 채택
enum VendingMachineError : Error {
  case missInput
  case notReceivedMoney
  case wantMoreMoney(wantMoeny : Int)
  case outOfStock
}
```

## throw

- 오류 발생의 여지가 있는 메서드는 `throws`를 사용하여 오류를 내포하는 함수임을 표시
- 함수 내부에서 `throw`로 발생한 오류 종류 작성

```swift
class VendingMachine  {
  // 저장 프로퍼티
  let price : Int = 100 // 가격
  var itemCount : Int = 5 // 잔여 아이템 갯수
  var depositedMoney : Int = 0 // 투입받은 금액
  
  // 투입 금액 메서드
  // 오류가 발생할 수 있는 메서드는 메서드명 뒤에 throws를 추가
	// guard 구문이 false면 throw로 에러 프로토콜이 있는 값을 반환 후 종료
  func receiveMoney(insertMoney receivedMoney: Int) throws {
    
    guard receivedMoney > 0 else {
      throw VendingMachineError.notReceivedMoney
    }
    
    depositedMoney += receivedMoney
    print("투입 금액은 \(receivedMoney)원입니다.")
  }
  
  // 아이템 판매 메서드
  func vend(numberOfItems numberOfItemsToVend : Int) throws -> String {
    
		// 구매수량 * 가격 = 최종 금액
    let theFinalPrice : Int = numberOfItemsToVend * price
    
		// 최종금액 - 잔여 투입 금액 = 부족한 금액
    let moneyMoreNeeded : Int = theFinalPrice - depositedMoney

    
    // 구매를 원하는 아이템 수량이 0보다 작으면 오류
    guard numberOfItemsToVend > 0 else
    {
      throw VendingMachineError.missInput
    }
    
    // 구매하려는 수량의 금액이 미리 투입한 금액보다 적으면 오류
    guard numberOfItemsToVend * price <= depositedMoney else
    {
		      // 추가로 필요한 금액 = 최종 가격 - 투입 금액
           throw VendingMachineError.wantMoreMoney(wantMoeny: moneyMoreNeeded)
    }
  
    // 원하는 구매 수량이 잔여 아이템 수량보다 많으면 오류
    guard itemCount >= numberOfItemsToVend else
    {
      throw VendingMachineError.outOfStock
    }
    
    // 정상처리 구문
    // 투입 금액 - 최종 가격
    depositedMoney -= theFinalPrice
    itemCount -= numberOfItemsToVend
    
    return "\(numberOfItemsToVend)개 제공했습니다. 남은 금액은 \(depositedMoney)원 입니다."
  }
}

// 자판기 인스턴스
var machine : VendingMachine = VendingMachine()

// 판매 결과를 담을 변수
// 이후에 나오는 try?의 결과로 오류가 발생하면 nil이 반환되기도 하기 때문에 Optional 타입으로 선언
var result : String?
```

## 오류 처리

- `throw` 한 오류를 받아서 처리하기 위한 코드도 작성해야 함
- 오류를 받아서 처리할 때는 아래의 선택지들이 있음
    - 던져진 오류가 무엇인지 판단하여 다시 문제를 해결
    - 다른 방법으로 시도
    - 사용자에게 오류를 알리고 선택 권한을 넘겨주어, 다음에 어떤 동작을 하게 할 것인지 결정하도록 유도
- 오류 발생의 여지가 있는 `throws` 함수(메서드)는 `try`를 사용하여 호출해야 함
    - 함께 활용하는 문법으로 `do-catch`, `try?`, `try!` 등이 있음

### `do-catch`

- 오류 발생의 여지가 있는 throws 함수(메서드)는 do-catch 구문을 활용하여 오류 발생에 대비

기본 구문

- 가장 정석적인 방법으로 모든 오류 케이스에 대응

```swift
// do-catch문
do
{
  // 오류 발생의 여지가 있는 throws 함수(메서드)는 try를 붙여서 호출
  try machine.receiveMoney(insertMoney: 0)
}
catch VendingMachineError.notReceivedMoney
{
  print("금액을 투입하지 않았습니다.")
} // 금액을 투입하지 않았습니다.

do
{
  result = try machine.vend(numberOfItems: 6)
}
catch VendingMachineError.missInput
{
  print("아이템 수량이 잘못 입력되었습니다.")
}
catch VendingMachineError.outOfStock
{
  print("수량이 부족합니다")
}
// K : throws에서 부족한 금액 (wantMoney: moneyMoreNeeded)가 enum에 반환되었고, catch에서 그 매개변수를 활용하려면 어떤 이름으로든 선언하여 사용하면 되는 듯
catch VendingMachineError.wantMoreMoney(let a)
{
  print("\(a)원이 부족합니다.")
}
// console : 600원이 부족합니다.

// K : itemCount = 5이고 구매 수량에 6을 적었기 때문에 품절 에러가 발생해야 하지만, 메서드 생성 시에 금액 부족에 대한 guard - throws문을 먼저 만들었기 때문에, 금액 부족에 대한 catch문이 더 아래에 있음에도 불구하고, 해당 구문으로 실행되었음. 의도하는 바에 따라 메서드에 오류 작성 순서를 고려해야 할 듯.
```

catch - switch

- catch문 내부에서 switch문으로 하나의 catch에서 다수의 오류 처리

```swift
// switch 구문을 사용하면 하나의 catch문으로도 처리 가능
do
{
  result = try machine.vend(numberOfItems: 0)
}
// catch문 자체에 throws로 받은 오류가 상수 error에 암시적으로 저장됨
catch // (let error)
{
  switch error
  {
    case VendingMachineError.missInput:
      print("아이템 수량이 잘못 입력되었습니다.")
      
    case VendingMachineError.wantMoreMoney(let a):
      print("\(a)원이 부족합니다.")
      
    case VendingMachineError.outOfStock:
      print("수량이 부족합니다.")
      
    default:
      print("알 수 없는 오류 \(error)")
  }
}
// console : 아이템 수량이 잘못 입력되었습니다.
```

오류의 종류만 확인할 때

- case별로 처리할 필요 없이, 오류의 종류만 확인하고 싶다면 catch 구문을 간략화할 수 있음

```swift
do
{
  result = try machine.vend(numberOfItems: -2)
}
catch
{
  // 전달받은 error의 종류만 print
  print(error)
  
  // catch문 발동 조건은 '오류가 발생하면'이기 때문에, error와 전혀 상관없는 내용을 작성하여도 됨
  print("A")
}
// console : missInput
```

오류 확인 및 처리가 필요하지 않을 때

- 오류 확인 및 처리 자체가 아예 필요 없다면, do 구문만 사용해도 무방
    - K : 실제로 catch문 없이 오류가 발생하면 해당 라인 아래로 실행이 되지 않음. 오류가 발생할 일이 없는 확신이 있을 때 쓰라는 얘기인건지, 버전의 차이로 다르게 작동하는 것인지 확인 필요

```swift
do
{
  result = try machine.vend(numberOfItems: 0)
}
// console error : An error was thrown and was not caught
// 해당 라인 아래로 실행이 중단
```

### `try?`와`try!`

- `try?`
    - 오류 발생에 대해 throw를 받지 않고, 결과값을 nil로 돌려받음
    - 오류 없이 정상 동작한다면 옵셔널 타입의 반환값을 돌려받음

```swift
try machine.receiveMoney(insertMoney: 300)

result = try? machine.vend(numberOfItems: 2)
print(result)
// console : Optional("2개 제공했습니다. 남은 금액은 100원 입니다.")

// 금액 부족으로 인해 오류 발생
result = try? machine.vend(numberOfItems: 2)
print(result)
// console : nil
```

- `try!`
    - 오류가 발생하지 않을 것이라는 강력한 확신을 가질 때 `try!`를 사용하면, 정상 동작 후에 바로 결과값을 돌려받음
        - K : 현재 버전에서는 동일한 예제로 진행 시, 옵셔널 타입의 결과값을 반환받음
    - 오류가 발생하면 런타임 오류가 발생하여 애플리케이션 동작이 중지

```swift
// try!
// 자판기 멤버 초기화
machine.itemCount = 5
machine.depositedMoney = 0

try machine.receiveMoney(insertMoney: 300)

result = try! machine.vend(numberOfItems: 2)
print(result)
// console : Optional("2개 제공했습니다. 남은 금액은 100원 입니다.")

// 예제에서는 위와 같이 실행 시, Optional이 벗겨진 타입으로 반환받는 것으로 나와있지만, 실제로는 try!로 실행하여도 Optional로 반환이 됨. 예제와 같은 결과를 받으려면 아래와 같이 실행해야 함
result = try? machine.vend(numberOfItems: 2)
print(result!)

result = try! machine.vend(numberOfItems: 2)
print(result)
// console error : 런타임 오류 발생!
```

# Reference

[iOS 프로그래밍을 위한 스위프트 기초](https://www.boostcourse.org/mo122/lecture/11321)
